site_name: QLDB Guide
site_author: Matt Lewis

# Repository
repo_name: AWS-South-Wales-User-Group/qldb-guide
repo_url: https://github.com/AWS-South-Wales-User-Group/qldb-guide
edit_uri: edit/main/docs/


theme:
  name: material
#  logo: assets/QLDB-Guide.svg
  font:
    text: Ubuntu

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode



# Page tree
nav:
  - Home: index.md
  - QLDB Guide:
    - Intro: guide/index.md
    - What is QLDB: guide/what-is-qldb.md
    - Database Freedom: guide/database-freedom.md
    - Setting Permissions: guide/setting-permissions.md
    - Concurrency Control: guide/concurrency-control.md
  - QLDB Demo:
    - Demo: demo/index.md
    - About the Demo: demo/architecture.md
    - Getting Started: demo/getting-started.md
  - QLDB Patterns:
    - Patterns: patterns/index.md
  - Blog Posts: 
    - Intro: blog/index.md
    - Securely Access QLDB from Private Subnet: blog/securely-access-qldb-from-private-subnet.md
    - Stream Data to ElasticSearch: blog/stream-data-from-qldb-to-elasticsearch.md
    - Stream Data to DynamoDB: blog/stream-data-from-qldb-to-dynamodb.md


markdown_extensions:
  - attr_list
  - md_in_html
