site_name: QLDB Guide
site_author: Matt Lewis
site_url: https://qldbguide.com/
site_description: >-
  An open guide to the AWS ledger database

# Repository
repo_name: AWS-South-Wales-User-Group/qldb-guide
repo_url: https://github.com/AWS-South-Wales-User-Group/qldb-guide
edit_uri: edit/main/docs/

theme:
  name: material
#  logo: assets/QLDB-Guide.svg
  font:
    text: Ubuntu

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# plugins
plugins:
  - social:
      cards_color:
        fill: indigo 
        text: "#FFFFFF"



# Page tree
nav:
  - Home: index.md
  - QLDB Guide:
    - Guide: guide/index.md
    - What is QLDB: guide/what-is-qldb.md
    - Data Design: guide/data-design.md
  - QLDB Demo:
    - Demo: demo/index.md
    - About the Demo: demo/architecture.md
    - Getting Started: demo/getting-started.md
    - Register Licence: demo/create-bicycle-licence.md
    - History: demo/history.md
    - Search: demo/search.md
    - Enquiry: demo/enquiry.md
  - QLDB Patterns:
    - Patterns: patterns/index.md
  - Blog Posts: 
    - Overview: blog/index.md
    - Redacting Data in QLDB: blog/redacting-data-in-qldb.md
    - Streaming Data to OpenSearch: blog/streaming-data-to-opensearch.md
    - Protecting Data in QLDB Ledger: blog/protecting-data-in-qldb.md
    - Concurrency Control in QLDB: blog/concurrency-control-in-qldb.md
    - Fine Grained Access Control in QLDB: blog/qldb-fine-grained-access-control.md
    - Securely Access QLDB from Private Subnet: blog/securely-access-qldb-from-private-subnet.md
    - Stream Processing with DynamoDB Streams and QLDB Streams: blog/stream-processing-with-qldb-and-dynamodb.md
    - Stream Data to ElasticSearch: blog/stream-data-from-qldb-to-elasticsearch.md
    - Stream Data to DynamoDB: blog/stream-data-from-qldb-to-dynamodb.md
  - QLDB Resources: https://github.com/mlewis7127/awesome-qldb

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
